spring:
  profiles:
    active: secret

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
